title: Medicina do Aprimoramento
description: > # this means to ignore newlines until "baseurl:"
  Medicina do aprimoramento.
  Ciência voltada ao aperfeiçoamento pessoal.
permalink: ':title/'
baseurl: "/medicinadoaprimoramento"
url: "https://vitruvia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
sitename: Medicina do aprimoramento
author: Thales Alexandre # add your name
author-img: VitruvianCoverSite.jpg # add your photo
about-site: Todo indivíduo tem direito a autonomia sobre o próprio corpo, e o conhecimento é a melhor ferramenta
  para concretizar esse direito.

social-instagram: medicinadoaprimoramento
social-facebook: medicinadoaprimoramento
#social-github:
#social-linkedin:
social-email: aprimoramentoconsultoria@gmail.com
author-instagram: _thalesalexandre

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
